services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=tickatch
      - POSTGRES_USER=tickatch
      - POSTGRES_PASSWORD=@@Tickatch01
    ports:
      - '5434:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql